### ISSUE TITLE
upload errors

### ISSUE THREAD

**Issue by selfagency** [jessicahayley/node-mastodon#6]
for some reason ~70% of the time i submit a media post, i get a missing image as the result.

**my code**
```
      if (!is.bad(img)) {
        console.log(`file exists: ${fs.existsSync(img)}`)
        const res = await M.post('media', {
          file: fs.createReadStream(img)
        })
        console.log(JSON.stringify(res.data))
        out.push(res.data.id)
      }
```

**the result**
```
stream: ./img/upload_wikimedia_org_wikipedia_commons_5_5d_Pan-bagnat_1_jpg.jpg
file exists: true
result: {"id":"72087","type":"unknown","url":"https://bofa.lol/files/original/missing.png","preview_url":"https://bofa.lol/files/small/missing.png","remote_url":null,"text_url":"https://bofa.lol/media/xgv6Lhvuj4gzXWcY3w4","meta":null,"description":null}
```

**Comment by hylyh** [comment]
If it's not happening all the time, I wonder if this is an issue with the instance itself? Can you reproduce on an instance that is more guaranteed to be stable? i.e. mastodon.social

**Comment by selfagency** [comment]
tbh, my server is probably more reliable than dot social. anyhow, if i add a delay after the upload but before the post is submitted it works better but is still a bit spotty.
